/**
 * Test harness: drives the app only through `app.fetch(new Request(...))` and
 * `app.ws.*`, with real P-256 keys generated by WebCrypto.
 */
import type { App } from "../src/core/app-contract.js";
import { createApp } from "../src/core/app.js";
import { decodeBase64Url, encodeBase64Url, utf8Encode } from "../src/core/base64url.js";
import { setDefaultPbkdf2Iterations } from "../src/core/crypto.js";
import { createMemoryPorts, type MemoryPorts, type MemoryPortsOverrides } from "../src/adapters/memory/index.js";
import type { AuthResponse, Conversation, Device, Envelope, Invite, User } from "../src/protocol/types.js";

// 600k PBKDF2 iterations take >1 s each on CI boxes; verification honours the stored count.
setDefaultPbkdf2Iterations(1_000);

export const ADMIN_KEY = "test-admin-key-0123456789";
export const BASE = "https://api.test";

export interface TestApp {
  app: App;
  ports: MemoryPorts;
}

export function makeApp(overrides?: MemoryPortsOverrides): TestApp {
  const ports = createMemoryPorts(overrides);
  return { app: createApp(ports), ports };
}

// ---------- keys & signatures ----------

export interface SigningKey {
  publicKey: string; // base64url SPKI
  privateKey: CryptoKey;
}

export async function genSigningKey(): Promise<SigningKey> {
  const kp = await crypto.subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, ["sign", "verify"]);
  const spki = new Uint8Array(await crypto.subtle.exportKey("spki", kp.publicKey));
  return { publicKey: encodeBase64Url(spki), privateKey: kp.privateKey };
}

export async function genEcdhPublicKey(): Promise<string> {
  const kp = await crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256" }, true, ["deriveBits"]);
  return encodeBase64Url(new Uint8Array(await crypto.subtle.exportKey("spki", kp.publicKey)));
}

export async function signBytes(key: CryptoKey, message: Uint8Array): Promise<Uint8Array> {
  return new Uint8Array(await crypto.subtle.sign({ name: "ECDSA", hash: "SHA-256" }, key, message as BufferSource));
}

/** Raw r||s signature (what WebCrypto and Android's P1363 conversion produce). */
export async function signAuth(key: CryptoKey, deviceId: string, nonce: string): Promise<string> {
  return encodeBase64Url(await signBytes(key, utf8Encode(`guftugu-auth:v1:${deviceId}:${nonce}`)));
}

/** Raw r||s -> DER SEQUENCE { INTEGER r, INTEGER s } (what Android's Signature API emits). */
export function rawToDer(raw: Uint8Array): Uint8Array {
  const int = (v: Uint8Array): number[] => {
    let i = 0;
    while (i < v.length - 1 && v[i] === 0) i++;
    let body = [...v.subarray(i)];
    if ((body[0] ?? 0) & 0x80) body = [0, ...body];
    return [0x02, body.length, ...body];
  };
  const r = int(raw.subarray(0, 32));
  const s = int(raw.subarray(32, 64));
  return new Uint8Array([0x30, r.length + s.length, ...r, ...s]);
}

export { decodeBase64Url, encodeBase64Url };

// ---------- requests ----------

export interface ReqOpts {
  body?: unknown;
  token?: string;
  admin?: boolean;
  headers?: Record<string, string>;
  noProtocol?: boolean;
  rawBody?: string;
}

export function request(method: string, path: string, opts: ReqOpts = {}): Request {
  const headers: Record<string, string> = { ...(opts.headers ?? {}) };
  if (!opts.noProtocol) headers["X-Guftugu-Protocol"] = "1";
  if (opts.token) headers["Authorization"] = `Bearer ${opts.token}`;
  if (opts.admin) headers["X-Admin-Key"] = ADMIN_KEY;
  let body: string | undefined;
  if (opts.rawBody !== undefined) body = opts.rawBody;
  else if (opts.body !== undefined) body = JSON.stringify(opts.body);
  if (body !== undefined) headers["Content-Type"] = "application/json";
  return new Request(`${BASE}${path}`, { method, headers, body });
}

export interface Result<T = any> {
  status: number;
  body: T;
}

export async function call<T = any>(app: App, method: string, path: string, opts: ReqOpts = {}): Promise<Result<T>> {
  const res = await app.fetch(request(method, path, opts));
  const text = await res.text();
  const body = text.length > 0 ? JSON.parse(text) : null;
  return { status: res.status, body };
}

export function errorCode(r: Result): string | undefined {
  return r.body?.error?.code;
}

// ---------- fixtures ----------

export interface Enrolled {
  user: User;
  device: Device;
  userId: string;
  deviceId: string;
  token: string;
  deviceKey: SigningKey;
  authKey: SigningKey | null;
  password: string;
}

export async function createInvite(
  app: App,
  opts: { displayName?: string; role?: "member" | "admin"; forUserId?: string; expiresInHours?: number; autoJoin?: string[] } = {},
): Promise<Invite> {
  const r = await call<Invite>(app, "POST", "/admin/invites", { admin: true, body: opts });
  if (r.status !== 201) throw new Error(`createInvite failed: ${r.status} ${JSON.stringify(r.body)}`);
  return r.body;
}

export async function enrollWithCode(
  app: App,
  inviteCode: string,
  opts: { displayName?: string; password?: string; withBiometric?: boolean; deviceName?: string } = {},
): Promise<Enrolled> {
  const deviceKey = await genSigningKey();
  const authKey = opts.withBiometric === false ? null : await genSigningKey();
  const encryptionPublicKey = await genEcdhPublicKey();
  const password = opts.password ?? "correct horse battery staple";
  const r = await call<AuthResponse>(app, "POST", "/enroll", {
    body: {
      inviteCode,
      displayName: opts.displayName ?? "Someone",
      password,
      devicePublicKey: deviceKey.publicKey,
      authPublicKey: authKey?.publicKey ?? null,
      encryptionPublicKey,
      device: { name: opts.deviceName ?? "Test phone", model: "Pixel 8", os: "Android 15", appVersion: "1.0.0" },
    },
  });
  if (r.status !== 201) throw new Error(`enroll failed: ${r.status} ${JSON.stringify(r.body)}`);
  return {
    user: r.body.user,
    device: r.body.device,
    userId: r.body.user.userId,
    deviceId: r.body.device.deviceId,
    token: r.body.session.token,
    deviceKey,
    authKey,
    password,
  };
}

/** Admin invite + enrollment in one go. */
export async function enrollUser(
  app: App,
  displayName: string,
  opts: { role?: "member" | "admin"; password?: string; withBiometric?: boolean; autoJoin?: string[] } = {},
): Promise<Enrolled> {
  const invite = await createInvite(app, { displayName, role: opts.role, autoJoin: opts.autoJoin });
  return enrollWithCode(app, invite.code, { displayName, password: opts.password, withBiometric: opts.withBiometric });
}

export async function challenge(app: App, deviceId: string): Promise<Result<{ nonce: string; expiresAt: number }>> {
  return call(app, "POST", "/auth/challenge", { body: { deviceId } });
}

/** Full challenge/verify round trip. */
export async function login(app: App, e: Enrolled, method: "biometric" | "password", password?: string): Promise<Result<AuthResponse>> {
  const ch = await challenge(app, e.deviceId);
  if (ch.status !== 200) return ch as unknown as Result<AuthResponse>;
  const key = method === "biometric" ? e.authKey?.privateKey : e.deviceKey.privateKey;
  if (!key) throw new Error("no key for method");
  const signature = await signAuth(key, e.deviceId, ch.body.nonce);
  const body: Record<string, unknown> = { deviceId: e.deviceId, nonce: ch.body.nonce, method, signature };
  if (method === "password") body.password = password ?? e.password;
  return call(app, "POST", "/auth/verify", { body });
}

export async function directConversation(app: App, a: Enrolled, b: Enrolled): Promise<Conversation> {
  const r = await call<Conversation>(app, "POST", "/conversations", { token: a.token, body: { type: "direct", memberId: b.userId } });
  if (r.status !== 200 && r.status !== 201) throw new Error(`direct failed: ${r.status} ${JSON.stringify(r.body)}`);
  return r.body;
}

export async function groupConversation(app: App, owner: Enrolled, name: string, members: Enrolled[]): Promise<Conversation> {
  const r = await call<Conversation>(app, "POST", "/conversations", {
    token: owner.token,
    body: { type: "group", name, memberIds: members.map((m) => m.userId) },
  });
  if (r.status !== 201) throw new Error(`group failed: ${r.status} ${JSON.stringify(r.body)}`);
  return r.body;
}

let connCounter = 0;

/** Open a fake WebSocket for `e`; returns the connection id. */
export async function connect(t: TestApp, e: Enrolled, connectionId = `conn_${++connCounter}`): Promise<string> {
  const r = await t.app.ws.onConnect(connectionId, e.token);
  if (!r.ok) throw new Error(`ws connect failed: ${r.status}`);
  return connectionId;
}

export function makeEnvelope(keyId: string, ctBytes = 24): Envelope {
  return {
    v: 1,
    keyId,
    iv: encodeBase64Url(crypto.getRandomValues(new Uint8Array(12))),
    ct: encodeBase64Url(crypto.getRandomValues(new Uint8Array(ctBytes))),
  };
}

export async function sendMessage(app: App, e: Enrolled, convId: string, keyId: string, clientId = crypto.randomUUID()) {
  return call(app, "POST", `/conversations/${convId}/messages`, {
    token: e.token,
    body: { clientId, sentAt: Date.now(), envelope: makeEnvelope(keyId) },
  });
}
